apiVersion: edna.graitdm.edu/v1
kind: EdnaJob
metadata:
  name: ednajob1
spec:
  import_key: in_test
  export_key: out_test
  jobname: ednajob1
  applicationname: controller
  filename: example
  jobcontext: ednaconf
  jobtype: internal
  jobimagetag: latest
  registryhost: localhost
  registryport: 5000
  jobvariablenames:
    - bootstrap_server
  jobvariablevalues:
    - "edna-cluster-kafka-bootstrap.kafka.svc-cluster.local"
    - value2
     

